###Welcome to Python Tutorial Part 1


### Basic Data Types

Strings

In [6]:
a = 'Hello'# String literals can use single quotes
print(a)
# a= 5
# print(a)
#a = 6.0
#a = "Hello"# or double quotes; it does not matter
# a = '''hello
# How are you'''# Triple quotes for sentences
print(a)
print(a, len(a))# print and len of string
# String concatenation

Hello
Hello
Hello 5


In [7]:
a = 6#casting to string using str and f
b = str(a)
print(type(a), type(b))

<class 'int'> <class 'str'>


In [16]:
s = 'hello '
print(s.capitalize())# Capitalize a string
print(s.upper())# Convert a string to uppercase; prints "HELLO"
print(s.rjust(2))# Right-justify a string, padding with spaces
print(s.center(7))# Center a string, padding with spaces
print(s.replace('l',"GG"))# Replace all instances of one substring with another
print("    hello  ".strip())# Strip leading and trailing whitespace

Hello 
HELLO 
hello 
 hello 
heGGGGo 
hello


In [17]:
print(s*10)# Print a string N Times*

hello hello hello hello hello hello hello hello hello hello 


In [19]:
#string as individual char
s = 'hello'
print(s[4])

o


Numbers

In [20]:
# integers and floats, type check
a = 5
b = 2.5
print(type(a), type(b))

<class 'int'> <class 'float'>


In [21]:
print(a+1)# Addition
print(b-1)# Subtraction
print(a*b)# Multiplication
print(a**2)# Exponentiation

6
1.5
12.5
25


In [25]:
print(a%3)# Modulus
print(a/2)# Division
print(a//2)# Floor Division

2
2.5
2


In [28]:
#increment and decrement
a = 1
a = a-1
print(a)
a -= 1
print(a)

0
-1


Booleans

In [31]:
a = True
b = False


print(a and b) # Logical AND;
print(a or b) # Logical OR;
print(not a) # Logical NOT;

False
True
False


### Containers

Lists

In [35]:
# Create a list
a = ['python', 'go', 'c++', 'java']
print(a[2])
# Negative indices count from the end of the list; prints "2"
print(a[-4])

c++
python


In [36]:
# Lists can contain elements of different types
a = ['python', 5, True, 'java']
print(a)

['python', 5, True, 'java']


In [39]:
# Add a new element to the end of the list
nums = list(range(5))
print(nums)
nums.append(5)
print(nums)
# Remove and return the last element of the list
popped_element = nums.pop()
print("popped value: ", popped_element)
print(nums)
# Sort

[0, 1, 2, 3, 4]
[0, 1, 2, 3, 4, 5]
popped value:  5
[0, 1, 2, 3, 4]


In [45]:
nums = list(range(5))# range is a built-in function that creates a list of integers
print(nums)# Prints "[0, 1, 2, 3, 4]"
print(nums[0:2])      # Get a slice from the start to index 2 (exclusive); prints "[0, 1]"
      # Get a slice of the whole list; prints ["0, 1, 2, 3, 4]"
print(nums[0:4]) 
print(nums[:-1])# Slice indices can be negative; prints ["0, 1, 2, 3]"
nums[2:4] = [7,8]
print(nums)# Assign a new sublist to a slice
      # Prints "[0, 1, 8, 9, 4]"
print(nums[::-1])     # reversing a list

[0, 1, 2, 3, 4]
[0, 1]
[0, 1, 2, 3]
[0, 1, 2, 3]
[0, 1, 7, 8, 4]
[4, 8, 7, 1, 0]


In [47]:
# use append() to add a single value and extend() to add multiple values
a = ['python', 'go', 'c++', 'java']
a.append(5)
print(a)
a.extend([7,8])
print(a)

['python', 'go', 'c++', 'java', 5]
['python', 'go', 'c++', 'java', 5, 7, 8]


Tuples

In [50]:
#same as list, but not mutable
b = (4,8,9,1,0)
print(b)
print(b[0])
b.append(1)

(4, 8, 9, 1, 0)
4


AttributeError: 'tuple' object has no attribute 'append'

Sets

In [71]:
animals = {'cat', 'dog', 6, 'horse', 'tiger', 'lion', 7, 8} #unordered
print(animals)
print('Fish' in animals)# Check if an element is in a set; prints "True"
# prints "False"
animals.add('fish')# Add an element to a set
print(animals)
animals.add('Fish')# Adding an element that is already in the set does nothing
print(animals)
animals.pop()# Remove an element from a set
print(animals)

{'dog', 'cat', 6, 7, 8, 'lion', 'tiger', 'horse'}
False
{'dog', 'cat', 6, 7, 8, 'lion', 'tiger', 'horse', 'fish'}
{'dog', 'cat', 6, 7, 8, 'lion', 'Fish', 'tiger', 'horse', 'fish'}
{'cat', 6, 7, 8, 'lion', 'Fish', 'tiger', 'horse', 'fish'}


Dictionaries

In [63]:
d = {'cat': 'cute', 'dog': 'big'}  # Create a new dictionary with some data
#dictionary = {key: value}
print(d['dog'])
     # Get an entry from a dictionary; prints "cute"
print('Cat' in d)     # Check if a dictionary has a given key; prints "True"

big
False


In [64]:
d['fish'] = 'wet'  # Set an entry in a dictionary
print(d['fish'])     # Prints "wet"

wet


In [65]:
 print(d.get('monkey', 'N/A')) # Get an element with a default; prints "N/A"
 print(d.get('fish', 'N/A'))  # Get an element with a default; prints "wet"

N/A
wet


In [66]:
del d['fish']    # Remove an element from a dictionary
print(d.get('fish', 'N/A'))# "fish" is no longer a key; prints "N/A"


N/A


In [68]:
nums= [0,1,2,3]
print(nums[:999]) #[0,1,2,3]

[0, 1, 2, 3]


### Conditional Statements

In [78]:
#if, else, elif
s1 = 80
s2 = 60
s3 = 70
if s1>s2:
    print("S2 is larger than S1")
# elif s2>s3:
#     print("S2 is less than S3")
# else:
#     print("else executed")


#  You can use IF statement without an else or without an elif
#     but you cannot use else without an If



S2 is larger than S1


In [80]:
a = 40
b = 50
print("A") if a > b else print("B") #shorthand

B


### Loops

In [92]:
# While Loop
# a = 1
# while a<10:
#     a += 1
#     print(a, a**2)


# For Loop (in list, range, string)
# for i in range(15): 
#     print(i,i**2)

# nums = [0,1,2,3]
# for i in nums:
#     print(i)
    
fr = 'abcde'
# for i in fr:
#     print(i)
 
string_length = len(fr)
print(string_length)

for i in range(5):
    print(fr[i])
    

5
a
b
c
d
e


In [94]:
# enumerate()
# animals = ['cat', 'dog', 'monkey']
# for idx, letter in enumerate(animals):
#     print(idx, letter)
    
    
# looping over dictionaries: key, value pairs, We always access the dictionarie values using their key
animals = {1:'cat', 2:'dog', 3:'monkey'}
for key, value in animals.items():
    print(key, value)

1 cat
2 dog
3 monkey


### Functions

In [99]:
#define a func, pass keyword
def sum():
      pass

In [100]:
#arguments
def sign(x): #x= 1
    if x>0:
        return 'positive'
    elif x<0:
        return 'negative'
    else:
        return 'Zero'

for x in [-1,0,1]:
    print(x, sign(x))

-1 negative
0 Zero
1 positive


In [101]:
def my_function(x):
  return x**2

# For such simple functions one may use lambdas:
my_lambda_function = lambda x: x**3

for i in range(5):# i = 0,1,2,3,4
  print(my_function(i), my_lambda_function(i))

0 0
1 1
4 8
9 27
16 64


In [102]:
def hello(name, loud=False):
    if loud: # this means if loud == True
        print('HELLO, {}'.format(name.upper()))
    else:
        print('Hello, {}!'.format(name,loud))
        
hello('Bob') # Bob False
hello('Fred', loud=True) #FRED True

Hello, Bob!
HELLO, FRED


# Numpy

In [104]:
#to import a package
import numpy as np
#import numpy 

1d Array

In [111]:
#Declare an empty array
arr1=np.array([]) #OR arr1=np.array(())
print("Empty array is = ",arr1)
a1=np.array(())
print("Empty array=",a1)

arr2=np.array([1,2,3,4,5])
print("Printing an array = ",arr2)

# #to print the element at given index
print("Element at index 3 is = ",arr2[3]) #4
print(arr2[1]) #2

# #to print type of array
print("Type of array is = ",type(arr2))

# #to print shape (or dimensions) of array
print("Shape of array is = ",arr2.shape)
print(a1.shape)

# #to change an element of an array
arr2[2]=10
print("After changing an element, array look like ",arr2)

# #to split an array
print("After splitting array in 2 parts",np.array_split(arr2, 2))
print(np.array_split(arr2,3))

Empty array is =  []
Empty array= []
Printing an array =  [1 2 3 4 5]
Element at index 3 is =  4
2
Type of array is =  <class 'numpy.ndarray'>
Shape of array is =  (5,)
(0,)
After changing an element, array look like  [ 1  2 10  4  5]
After splitting array in 2 parts [array([ 1,  2, 10]), array([4, 5])]
[array([1, 2]), array([10,  4]), array([5])]


2d array

In [115]:
#to create a 2-D array
arr3=np.array([[1,2,3,4],[5,6,7,8]])


#arr3=np.array([1,2,3],[4,5,6]) #this is wrong, it will throw an error

print("Printing 2-D array")
print(arr3)

#to print shape of an array
print("Shape of array is = ",arr3.shape)

#to print element at given index
print("Element at given index is = ",arr3[0][2])

Printing 2-D array
[[1 2 3 4]
 [5 6 7 8]]
Shape of array is =  (2, 4)
Element at given index is =  3


Various functions to create array

In [116]:
#Create an array of all zeros
arr4=np.zeros((3,2))
print(arr4)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [118]:
#Create an array of all ones
arr5=np.ones((4,2))
print(arr5)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [120]:
#Create a constant array
arr6=np.full((4,5),10)
print(arr6)

[[10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]
 [10 10 10 10 10]]


In [122]:
#Create n*n Identity matrix
'''
2*2 Identity matrix
1 0
0 1
'''
arr7=np.eye(6)
print(arr7)

[[1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]


In [124]:
#Create an array filled with random values
arr8=np.random.random((1,2))
print(arr8)
arr9 = np.random.randint(100,250, size=(5,4))
print(arr9)

[[0.83291293 0.19655615]]
[[108 238 168 112]
 [173 205 157 105]
 [223 116 214 124]
 [150 135 121 113]
 [226 141 147 239]]


Array Slicing

In [125]:
#Example
arr9=np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
print(arr9)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [126]:
'''
Suppose we want to print the following subarray from above array -
[[ 7  8  9]
 [12 13 14]]
''' 
print(arr9[1:3,1:4])
#print(arr9[0:2,2:4])

[[ 7  8  9]
 [12 13 14]]


Array Modification

In [127]:
#to modify an element in an array
arr9[1][2]=20
print(arr9)

[[ 1  2  3  4  5]
 [ 6  7 20  9 10]
 [11 12 13 14 15]]


Changing the dimensions

In [128]:
#to reshape an array
arr10=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print("Before reshaping -")
print(arr10)
arr11=np.reshape(arr10,(3,4))
print("After reshaping -")
print(arr11)

Before reshaping -
[ 1  2  3  4  5  6  7  8  9 10 11 12]
After reshaping -
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


Matrices

In [129]:
#to create a matrix
mat1=np.matrix([[1,2,3],[4,5,6],[7,8,9]])
print(mat1)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [130]:
#to print diagonal of a matrix
print(np.diagonal(mat1))

[1 5 9]


In [131]:
mat2=np.matrix([[4,5,6],[7,8,9],[1,2,3]])
'''
A=
a b
c d

B=
e f
g h

A+B=
a+e b+f
c+g d+h
'''

#Element-wise addition
print("Addition - ")
print(np.add(mat1,mat2))

#Element-wise Subtraction
print("Subtraction - ")
print(np.subtract(mat1,mat2))

#Element-wise multiplication
print("Multiplication - ")
print(np.multiply(mat1,mat2))

#Element-wise division
print("Division -")
print(np.divide(mat1,mat2))

Addition - 
[[ 5  7  9]
 [11 13 15]
 [ 8 10 12]]
Subtraction - 
[[-3 -3 -3]
 [-3 -3 -3]
 [ 6  6  6]]
Multiplication - 
[[ 4 10 18]
 [28 40 54]
 [ 7 16 27]]
Division -
[[0.25       0.4        0.5       ]
 [0.57142857 0.625      0.66666667]
 [7.         4.         3.        ]]


In [132]:
#Matrix Multiplication or Dot Product
print(mat1*mat2)

#Second Approach
print(np.dot(mat1,mat2))

[[ 21  27  33]
 [ 57  72  87]
 [ 93 117 141]]
[[ 21  27  33]
 [ 57  72  87]
 [ 93 117 141]]


In Matrix when we use * we get dot product but when we use * on np arrays we get element wise multiplication

In [133]:
a1=np.array([[1,2,3],[4,5,6],[7,8,9]])
a2=np.array([[4,5,6],[7,8,9],[1,2,3]])
print(a1*a2)
print(np.dot(a1,a2))

[[ 4 10 18]
 [28 40 54]
 [ 7 16 27]]
[[ 21  27  33]
 [ 57  72  87]
 [ 93 117 141]]
